config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  resources :activities do
  member do
    post 'favorites', to: 'favorites#create', as: :favorite
    delete 'favorites', to: 'favorites#destroy'
  end
    resources :reviews, only: [ :new, :create ]
    collection do
      get "event", to: "activities#event"
    end
  end
  resources :messages, only: [:create]

  resources :profiles, only: [:new, :create, :edit, :update]

  devise_for :users

  get '/users/dashboard', to: 'users#show', as: 'dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
def create
  @activity = Activity.find(params[:id])
  @favorite = Favorite.new
  @favorite.activity = @activity
  @favorite.user = current_user
  @favorite.save
  respond_to do |format|
    format.html { redirect_to activity_path(@activity)}
    format.js
  end
end

def destroy
  @activity = Activity.find(params[:id])
  all_favorites = @activity.favorites.where(user: current_user)
  all_favorites.each do |fav|
    fav.destroy
  end
  respond_to do |format|
    format.html { redirect_to activity_path(@activity)}
    format.js
  end
end

private

  def favorite_params
    params.require(:favorite).permit(:heart)
  end
end

app/views/favorites/_fav_card.html.erb
<% if current_user.nil? %>
  <%= link_to new_user_session_path, id: 'hearticn' do %>
    <i class="far fa-heart"></i>
  <% end %>

<% else %>
  <% if !favorite %>
    <%= link_to favorite_activity_path(activity), method: :post, id: 'hearticn', remote: true do %>
      <i class="far fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to favorite_activity_path(activity), method: :delete, id: 'hearticn', remote: true do %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
document.querySelector("[data-heart='<%= @activity.id %>']").innerHTML = "<%= j render 'favorites/fav_card', activity: @activity, favorite: true %>"

app/views/favorites/destroy.js.erb
document.querySelector("[data-heart='<%= @activity.id %>']").innerHTML = "<%= j render 'favorites/fav_card', activity: @activity, favorite: false %>"