config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  resources :activities do
  member do
    post 'favorites', to: 'favorites#create', as: :favorite
    delete 'favorites', to: 'favorites#destroy'
  end
    resources :reviews, only: [ :new, :create ]
    collection do
      get "event", to: "activities#event"
    end
  end
  resources :messages, only: [:create]

  resources :profiles, only: [:new, :create, :edit, :update]

  devise_for :users

  get '/users/dashboard', to: 'users#show', as: 'dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :messages
  has_many :activities
  has_many :reviews
  has_many :favorites, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @activities = Activity.all
  end
end

app/views/users/show.html.erb
<div class="container">
  <div class="avatar">
    <%= render 'shared/avatar' %>
  </div>
  <div class="name">
    <h3>Bienvenue <%= @user.profile.first_name %></h3>
    <%= link_to "modifier mon profil", edit_profile_path(current_user), class: "sous-titre" %>
  </div>
  <%# <div class="col-12 sm-3"> %>
  <div class="display-activity container-fluid">
    <div class="valeur event_l", id="aliment">
      <%= image_tag "Alimentation-n.png", class: "icon-alimentation" %>
      <div>
        <h5>MES EPICERIES PREFEREES</h5>
        <% @user.favorites.joins(:activity).where(activities: { category: 'Alimentation' }).each do |favorite| %>
        <% end %>
      </div>
    </div>
    <div class="select aliment row" hidden>
      <% @user.favorites.joins(:activity).where(activities: { category: 'Alimentation' }).each do |favorite| %>
        <%= render  "shared/activity_cards", activity: favorite.activity %>
      <% end %>
    </div>
    <div class="valeur event_l", id="restau">
      <%= image_tag "Restaurant-n.png", class: "icon-restaurant" %>
      <div>
        <h5>MES RESTAURANTS PREFERES</h5>
        <% @user.favorites.joins(:activity).where(activities: { category: 'Restaurant' }).each do |favorite| %>
        <% end %>
      </div>
    </div>
    <div class="select restau" hidden>
      <% @user.favorites.joins(:activity).where(activities: { category: 'Restaurant' }).each do |favorite| %>
        <%= render  "shared/activity_cards", activity: favorite.activity %>
      <% end %>
    </div>
    <div class="valeur event_l", id="shop">
      <%= image_tag "Shop-n.png", class: "icon-shop" %>
      <div>
        <h5>MES SHOPS PREFERES</h5>
        <% @user.favorites.joins(:activity).where(activities: { category: 'Shop' }).each do |favorite| %>
        <% end %>
      </div>
    </div>
    <div class="select shop" hidden>
      <% @user.favorites.joins(:activity).where(activities: { category: 'Shop' }).each do |favorite| %>
        <%= render  "shared/activity_cards", activity: favorite.activity %>
      <% end %>
    </div>
    <div class="valeur event_l", id="atelier">
      <%= image_tag "DIY-n.png", class: "icon-DIY" %>
      <div>
        <h5>MES ATELIERS PREFERES</h5>
        <% @user.favorites.joins(:activity).where(activities: { category: 'Atelier' }).each do |favorite| %>
        <% end %>
      </div>
    </div>
    <div class="select atelier" hidden>
      <% @user.favorites.joins(:activity).where(activities: { category: 'Atelier' }).each do |favorite| %>
        <%= render  "shared/activity_cards", activity: favorite.activity %>
      <% end %>
    </div>
    <div class="valeur event_l", id="evenement">
      <%= image_tag "Event-n.png", class: "icon-event" %>
      <div>
        <h5>MES EVENTS</h5>
        <% @user.favorites.joins(:activity).where(activities: { category: 'Event' }).each do |favorite| %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="select evenement" hidden >
    <% @user.favorites.joins(:activity).where(activities: { category: 'Event' }).each do |favorite| %>
      <%= render  "shared/activity_cards", activity: favorite.activity %>
    <% end %>
  </div>
</div>
<%# </div> %>
<script>
  var button = document.querySelectorAll('.event_l')
  button.forEach((icon)=> {
    icon.addEventListener('click', function(event){
      var all = document.querySelectorAll('.select');
      var elementSelect = document.querySelectorAll(`.select.${event.currentTarget.id}`);
      all.forEach((element) => {
        element.setAttribute('hidden', true);
      })
      elementSelect.forEach((element) => {
        element.removeAttribute('hidden');
      })
    })
    } )
</script>