config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  resources :activities do
  member do
    post 'favorites', to: 'favorites#create', as: :favorite
    delete 'favorites', to: 'favorites#destroy'
  end
    resources :reviews, only: [ :new, :create ]
    collection do
      get "event", to: "activities#event"
    end
  end
  resources :messages, only: [:create]

  resources :profiles, only: [:new, :create, :edit, :update]

  devise_for :users

  get '/users/dashboard', to: 'users#show', as: 'dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_activity_cards.html.erb
<div class="col-6 sm-3">
  <%= link_to activity_path(activity), class: "activity-link-show" do %>
    <div class="activity-card">
      <%= cl_image_tag activity.photo, class: "activity-pic" %>
      <div class="info-event">
        <h2><strong><%= activity.name %></strong></h2>
        <div>
          <p><%= activity.city %> (<%= activity.zipcode %>)</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_avatar.html.erb
<%= cl_image_tag current_user.profile.photo, class: "avatar", alt: "avatar" %>

app/views/shared/_button_fill.html.erb
<button class="EdgeButton--primary">GoGreenR</button>

app/views/shared/_button_transp.html.erb
<button class="EdgeButton--secondary"></button>

app/views/shared/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>">
  </div>
<% end %>

app/views/shared/_heart.html.erb
<a class="heart">
  <p class="glyphicon glyphicon-heart glyphicon-heart-empty"></p>
</a>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if current_user && current_user.profile && current_user.profile.photo %>
          <%= cl_image_tag current_user.profile.photo, class: "avatar-bordered", id: "navbarDropdown" %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to "Je recherche", activities_path, class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "J'ajoute", new_activity_path, class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "Agenda des events", event_activities_path, class: "dropdown-item" %>
      </li>
      <li class="nav-item">
        <%= link_to "Qui sommes-nous?", root_path(anchor: "values"), class: "dropdown-item" %>
      </li>
      <% if current_user %>
        <%= link_to "Mon espace", dashboard_path(current_user), class: "dropdown-item" %>
        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      <% else %>
        <%= link_to "Je me connecte", new_user_session_path, class: "dropdown-item" %>
        <%= link_to "Je m'enregistre", new_user_registration_path, class: "dropdown-item" %>
      <% end %>
      <li class="nav-item">
      </li>
    </li>
  </ul>
</div>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <input type="text" placeholder="Je cherche...">
  <div class="search"></div>
</div>

app/views/shared/_stars.html.erb
<span class="rating_stars">
  <% if activity.reviews.count > 0 %>
    <% activity.reviews.average(:rate).round.times do %>
      <span class="fas fa-star" ></span>
    <% end %>
    <% (5 - activity.reviews.average(:rate).round).times do %>
      <span class="far fa-star" ></span>
    <% end %>
    <span> (<%= activity.reviews.count %>)</span>
  <% else %>
    <% 5.times do %>
      <span class="far fa-star" ></span>
    <%end%>
  <%end%>
</span>

app/views/shared/index.html.erb
<h1>Profiles#index</h1>
<p>Find me in app/views/profiles/index.html.erb</p>