config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  resources :activities do
  member do
    post 'favorites', to: 'favorites#create', as: :favorite
    delete 'favorites', to: 'favorites#destroy'
  end
    resources :reviews, only: [ :new, :create ]
    collection do
      get "event", to: "activities#event"
    end
  end
  resources :messages, only: [:create]

  resources :profiles, only: [:new, :create, :edit, :update]

  devise_for :users

  get '/users/dashboard', to: 'users#show', as: 'dashboard'

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord

  CATEGORIES = [
    {
      image: 'alimentation',
      label: 'Alimentation',
      slug: 'alimentation'
    },
    {
      image: 'DIY',
      label: 'DIY',
      slug: 'DIY'
    },
    {
      image: 'restaurant',
      label: 'Restaurant',
      slug: 'restaurant'
    },
    {
      image: 'shopping',
      label: 'Shop',
      slug: 'shopping'
    },
    {
      image: 'event',
      label: 'Event',
      slug: 'event'
    },
  ]
  # Activity::CATEGORIES.map {|c| c[:label] }
  belongs_to :user
  geocoded_by :address
  has_many :messages, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :category, inclusion: { in: CATEGORIES.map {|c| c[:label] } }
  validates :street, :zipcode, :city, presence: true

  def address
    [street, zipcode, city].compact.join(', ')
  end


  mount_uploader :photo, PhotoUploader
  after_validation :geocode
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :event, :show]
  before_action :set_activity, only: [:show, :edit, :update]

  def index
    @activities = Activity.where.not(latitude: nil, longitude: nil)
    @favorite = isfavorite?(@activity)
    @markers = @activities.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        image_url: helpers.asset_url("#{activity.category}.png"),
        activity: activity.category,
        infoWindow: render_to_string(partial: "infowindow", locals: { activity: activity })
      }
    end
  end

  def show
    @favorite = isfavorite?(@activity)
    @message = Message.new
    # @message.activity_id = @activity[:id]
    # @message.user_id = current_user[:id]
    session[:current_path] = activity_path(@activity)
    @messages = @activity.messages
    @review = Review.new
    @review.activity = @activity
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @activity.update(activity_params)
    if @activity.save
      redirect_to activity_path(@activity)
    else
      render :edit
    end
  end

  def event
    @activities = Activity.order('starting_date ASC').all
  end

  private

  def isfavorite?(activity)
    !Favorite.find_by(user: current_user, activity: activity).nil?
  end

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :photo, :description, :category, :street, :zipcode, :city, :starting_date, :ending_date)
  end
end

app/views/activities/_cards_event.html.erb
  
<div class="card-event">
  <% unless current_user.nil? %>
    <% if activity.favorites.find_by(user: current_user).nil? %>
      <i class="far fa-heart"></i>
    <% else %>
      <i class="fas fa-heart"></i>
    <% end %>
  <% end %>
  <%= cl_image_tag activity.photo, class: "event-pic" %>
  <div id="heart" data-heart="<%= activity.id %>">
    <%= render 'favorites/fav_card',activity: activity, favorite: activity.favorites.find_by(user: current_user) %>
  </div>
  <%= link_to activity_path(activity), class: "activity-link-show" do %>
    <div class="info-event">
      <h3 style="font-size: 12px"><strong>Du <%= activity.starting_date.strftime("%d-%m-%Y") %> au <%= activity.ending_date.strftime("%d-%m-%Y") %> </strong></h3>
      <h2><strong><%= activity.name %></strong></h2>
      <div>
        <p><%= activity.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/activities/_infowindow.html.erb
<div class= mapbox>
  <%= link_to activity_path(activity), class: "activity-link-show" do %>
  <div class="haut">
    <%= cl_image_tag(activity.photo, height: 100, width: 200, crop: :fill,) %>
    <% unless current_user.nil? %>
      <% if activity.favorites.find_by(user: current_user).nil? %>
        <i class="far fa-heart"></i>
      <% else %>
        <i class="fas fa-heart"></i>
      <% end %>
    <% end %>
  </div>
    <div class="mapbox-title">
      <h5><%= activity.name %></h5>
        <%= render 'shared/stars', activity: activity %>
    <div class="mapbox-address">
      <p><%= activity.address %></p>
    </div>
    <div class="mapbox-description">
      <p><%= activity.description %></p>
    </div>
  <% end %>
</div>

app/views/activities/_message_box.html.erb
<div class="messages">
  <% @activity.messages.each do |message| %>
    <div class="message <%= current_user && (current_user.id == message.user.id) ? "owner" : '' %>">
      <div class="message-infos">
        <p class="message-infos-author"><%= message.user.profile.nickname %></p>
      </div>
      <div class="message-body">
        <%= message.content %>
      </div>
    </div>
  <% end %>
</div>
<% content_for :after_js do %>
  <script>
    function scrollLastMessageIntoView() {
      const messages = document.querySelectorAll('.message');
      const lastMessage = messages[messages.length - 1];
      lastMessage.scrollIntoView();
    }

    App['activity_<%= @activity.id %>'] = App.cable.subscriptions.create({ channel: 'ActivityChannel',
    activity_id: <%= @activity.id %> },
      { received: (data) => {
        console.log(data)
        if (data.type === 'message') {
        const messagesContainer = document.querySelector(".messages");
        const currentUserId = <%= current_user.nil? ? '' : current_user.id %>

        messagesContainer.insertAdjacentHTML('beforeend',
         `
          <div class="message ${data.data.message.user_id === currentUserId ? 'owner' : ''}">
             <div class="message-infos">
               <p class="message-infos-author">${data.data.sender}</p>
             </div>
             <div class="message-body">
               ${data.data.message.content}
             </div>
           </div>
          `
        );
        scrollLastMessageIntoView();
        }
      }
      })
  </script>
<% end %>

app/views/activities/_messages_send_form.html.erb
<div id="create-message">
 <% if current_user != nil %>
   <%= simple_form_for @message, remote: true, id: "form_id_here" do |f| %>
     <%= f.input :content, label: false %>
     <input name="message[activity_id]" type="hidden" value="<%= @activity.id %>">
     <%= button_tag type: 'submit', class: "message-form-button" do %>
      <i class="far fa-paper-plane"></i>
     <% end %>
   <% end %>
 <% else %>
   <a id="message-form-signin" href="/users/sign_in">Connectez-vous pour envoyer un message</a>
 <% end %>
</div>
<script>
 document.getElementById("message_content").addEventListener("keypress", function(event) {
   if (event.which == 13) {
     console.log("enter pressed");
       event.preventDefault();
       document.querySelector(".message-form-button").click();
     var messageInput = document.getElementById('message_content')
     if (messageInput) {
       messageInput.value = ""
     }
   }
 });
</script>

app/views/activities/create.html.erb
<h1>Activities#create</h1>
<p>Find me in app/views/activities/create.html.erb</p>

app/views/activities/edit.html.erb
<div class="container new-activity">
  <div class="form-img-bckg"><%= image_tag "Logo3.png" %></div>
  <br>
  <br>
  <br>
  <center>
    <h1> Modifiez les informations sur cette activité!</h1>
  </center>
  <div class="create-activity-form" >
    <%= simple_form_for @activity, class: "m-" do |a| %>
      <%= a.input :category,
          label: "Que souhaitez-vous ajouter?",
          collection: Activity::CATEGORIES.map {|c| c[:label] }%>
      <%= a.input :name,
          label: "Nom",
          placeholder: "Entrez le nom du lieu ou de l'évènement" %>
      <%= a.input :description, label: "Une petite description",
          placeholder: "Faites nous réver!" %>
      <%= a.input :street, label: "Rue",
          placeholder: "1, rue de la bonne humeur" %>
      <%= a.input :zipcode, label: "Code postal",
          placeholder: "75000" %>
      <%= a.input :city, label: "Ville",
          placeholder: "Paris" %>
      <div id="date-details">
        <%= a.input :starting_date, label: "Date de début", as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= a.input :ending_date, label: "Date de fin", as: :string, required: false, input_html: {class: "datepicker"} %>
      </div>
      <%= a.input :photo %>
      <%= a.input :photo_cache, as: :hidden %>
      <center>
        <%= a.button :submit, "Je partage !", class: "EdgeButton--primary" %>
      </center>
    <% end %>
  </div>
</div>
<script>
  const category = document.querySelector('#activity_category');
  const hiddenpart = document.querySelector('#date-details');
  hiddenpart.setAttribute('hidden', true);
  category.addEventListener("change", (event) => {
    console.log(event.currentTarget.value);
    if (event.currentTarget.value === 'Event') {
      hiddenpart.removeAttribute('hidden');
    } else {
      hiddenpart.setAttribute('hidden', true);
    }
  });
</script>

app/views/activities/event.html.erb
<div class="container">
  <h2> Tous les events</h2>
  <div class="grid">
    <% @activities.each do |activity| %>
      <% if activity.category == "Event" %>
        <%= render "activities/cards_event", activity: activity %>
      <% end %>
    <% end %>
    <div class="ajout">
      <%= link_to "J'ajoute un event!", new_activity_path, class: "border EdgeButton--secondary" %>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<div class="the_map">
<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >
    <%= image_tag "Truc_arrondi.png", id: "fond", class: "mapboxgl-ctrl-top-left" %>

    <%= image_tag "Logo3.png", id: "gros_logo", class: "mapboxgl-ctrl-top-left" %>
  </div>
  <div class='calculation-box'>
    <div> <%= image_tag "Event-n", class: "activity_filter", id: "Event" %></div>
    <div> <%= image_tag "Alimentation-n", class: "activity_filter", id: "Alimentation" %></div>
    <div> <%= image_tag "DIY-n", class: "activity_filter", id: "DIY" %></div>
    <div> <%= image_tag "Restaurant-n", class: "activity_filter", id: "Restaurant" %></div>
    <div> <%= image_tag "Shop-n", class: "activity_filter", id: "Shop" %></div>
    <div> <%= image_tag "Logo3-simple-plein", class: "activity_filter", id: "all" %></div>
  </div>

  <div class='sidebar'>
    <%= link_to new_activity_path do %> <i class="fas fa-plus-circle"></i> <% end %>
    <%= link_to event_activities_path do %> <i class="far fa-calendar"></i> <% end %>
    <%= link_to root_path(anchor: "values") do %> <i class="fas fa-info"></i> <% end %>

  </div>
</div>


<script>
  var allIcons = document.querySelectorAll('.activity_filter');

  allIcons.forEach( (icon) => {
    icon.addEventListener('click', function(event) {
      var elementSelect = document.querySelectorAll(`.marker.${event.target.id}`);
      var all = document.querySelectorAll('.marker');
          if (event.target.id === 'all') {
            all.forEach((element) => {
              element.style.visibility = 'visible'
            })
          } else {
            all.forEach((element) => {
              element.style.visibility = 'hidden'
            })
            elementSelect.forEach((element) => {
              element.style.visibility = 'visible'
            })
          }
    });
  });
</script>

app/views/activities/new.html.erb
<div class="container new-activity">
  <div class="form-img-bckg"><%= image_tag "Logo3.png" %></div>
  <br>
  <br>
  <br>
  <br>
  <center>
    <h1> A vous de partager!</h1>
  </center>
  <div class="create-activity-form" >
    <%= simple_form_for @activity, class: "m-" do |a| %>
      <%= a.input :category,
          label: "Que souhaitez-vous ajouter?",
          collection: Activity::CATEGORIES.map {|c| c[:label] }%>
      <%= a.input :name,
          label: "Nom",
          placeholder: "Nom du lieu ou de l'event" %>
      <%= a.input :description, label: "Une petite description",
          placeholder: "Faites nous réver..." %>
      <%= a.input :street, label: "Rue",
          placeholder: "1, rue de la bonne humeur" %>
      <%= a.input :zipcode, label: "Code postal",
          placeholder: "75000" %>
      <%= a.input :city, label: "Ville",
          placeholder: "Paris" %>
      <div id="date-details">
        <%= a.input :starting_date, label: "Date de début", as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= a.input :ending_date, label: "Date de fin", as: :string, required: false, input_html: {class: "datepicker"} %>
      </div>
      <%= a.input :photo %>
      <%= a.input :photo_cache, as: :hidden %>
      <center>
        <%= a.button :submit, "Je partage !", class: "EdgeButton--primary" %>
      </center>
    <% end %>
  </div>
</div>
<script>
  const category = document.querySelector('#activity_category');
  const hiddenpart = document.querySelector('#date-details');
  hiddenpart.setAttribute('hidden', true);
  category.addEventListener("change", (event) => {
    console.log(event.currentTarget.value);
    if (event.currentTarget.value === 'Event') {
      hiddenpart.removeAttribute('hidden');
    } else {
      hiddenpart.setAttribute('hidden', true);
    }
  });
</script>

app/views/activities/show.html.erb
<div class="event-pic-show">
  <%= cl_image_tag @activity.photo %>
  <div id="heart" data-heart="<%= @activity.id %>">
    <%= render 'favorites/fav_card', activity: @activity, favorite: @favorite %>
  </div>
</div>
<div class="container">
  <div class="event-txt-show">
    <div class="categ">
      <%= image_tag "#{@activity.category}-n.png" %>
    </div>
    <h1><strong><%= @activity.name %></strong> - <%= link_to edit_activity_path(@activity) do  %>
        <span><i class="far fa-edit"></i></span>
      <% end %>
    </h1>
    <h2>
      <div class="moyen"><%= render 'shared/stars', activity: @activity %></div>
    </h2>
    <div class = "d-flex star-rating justify-content-between">
      <% unless current_user.nil? %>
        <% if @activity.reviews.pluck(:user_id).include?(current_user.id)  %>
          <%= "Vous avez déjà voté" %>
        <% elsif %>
          <%= simple_form_for([@activity, @review], html: { class: "review_form" }) do |r| %>
            <%= r.input :rate, class: "shadow-sm p-3 mb-5 bg-white rounded", label: "donnez votre avis :", collection: [1, 2, 3, 4, 5 ] %>
            <%= r.button :submit, class: "d-none" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="avg-rate-display">
      <% if @activity.starting_date.blank? == false %>
        <p>Du <%= @activity.starting_date.strftime("%d-%m-%Y") %> au <%= @activity.ending_date.strftime("%d-%m-%Y") %></p>
      <% end %>
    </div>
    <h2>Adresse: </h2>
    <p><i><%= @activity.street %>, <%= @activity.zipcode %>, <%= @activity.city %>.</i></p>
    <% if @activity.url.blank? == false %>
      <span><%= link_to "Site web", @activity.url, target: :_blank, class: "url-show-activity"%></span>
    <% end %>
    <h2>Description:</h2>
    <p><%= @activity.description %></p>
    <div class="border-bottom"></div>
    <h2>Dialoguez avec la communauté : </h2>
  </div>
  <%= render 'message_box', activity: @activity %>
  <%= render 'messages_send_form', activity: @activity%>
</div>

app/views/activities/update.html.erb
<h1>Activities#update</h1>
<p>Find me in app/views/activities/update.html.erb</p>